CC=g++ # This is the main compiler
#CC=clang --analyze # and comment out the linker last line for sanity

SRCDIR=src/main
BUILDDIR=build/main
TARGETDIR=bin
TARGET=$(TARGETDIR)/xoraan

TESTDIR=src/test
TESTBUILDDIR=build/test
TESTTARGET=$(TARGETDIR)/xoraan-test

SRCEXT=cpp
# main file needs to be excluded from the test executable,
# because test runs have own main function provided by gtest_main library.
MAINFILE=main.$(SRCEXT)
# Application sources (no test sources).
SOURCES=$(shell find $(SRCDIR) -type f -name *.$(SRCEXT))
# Test sources only.
TESTSOURCES=$(shell find $(TESTDIR) -type f -name *.$(SRCEXT))
# Application objects generated by compiler (no test objects).
OBJECTS=$(patsubst $(SRCDIR)/%,$(BUILDDIR)/%,$(SOURCES:.$(SRCEXT)=.o))
# Application objects used to link against (no main object, no test objects).
LINKEDOBJECTS=$(shell echo $(OBJECTS) | sed -e s@$(BUILDDIR)/$(MAINFILE:.$(SRCEXT)=.o)@@)
# Test objects generated by compiler from test sources only.
TESTOBJECTS=$(patsubst $(TESTDIR)/%,$(TESTBUILDDIR)/%,$(TESTSOURCES:.$(SRCEXT)=.o))
# All objects neede for tests to run
# (test objects and those we are linking against).
TSOBJECTS=$(TESTOBJECTS) $(LINKEDOBJECTS)

CFLAGS=-g -std=c++11 # -Wall
LIB=-pthread -llog4cpp -lgtest -lgtest_main
INC= #-Iinclude
TESTINC=-Isrc/main

all: $(TARGET) $(TESTTARGET)

$(TARGET): $(OBJECTS)
	@echo $(OBJECTS)
	@echo $(LINKEDOBJECTS)
	@echo "Linking..."
	@mkdir -p $(TARGETDIR)
	$(CC) $^ -o $(TARGET) $(LIB)

$(TESTTARGET): $(TSOBJECTS)
	@echo "Linking tests..."
	@mkdir -p $(TARGETDIR)
	$(CC) $^ -o $(TESTTARGET) $(LIB)

$(BUILDDIR)/%.o: $(SRCDIR)/%.$(SRCEXT)
	@echo "Building..."
	@mkdir -p $(BUILDDIR) $(shell dirname $@)
	$(CC) $(CFLAGS) $(INC) -c -o $@ $<

$(TESTBUILDDIR)/%.o: $(TESTDIR)/%.$(SRCEXT)
	@echo "Building tests..."
	@mkdir -p $(TESTBUILDDIR) $(shell dirname $@)
	$(CC) $(CFLAGS) $(TESTINC) -c -o $@ $<

clean:
	@echo " Cleaning..."; 
	$(RM) -r $(BUILDDIR) $(TARGET) $(TESTBUILDDIR) $(TESTTARGET)

